// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0e8NbSgg2vx_MZfpC9YMZP8BxRVWczp0',
    appId: '1:333671428088:web:c41697dcb80ba4d336700d',
    messagingSenderId: '333671428088',
    projectId: 'niramana-setu',
    authDomain: 'niramana-setu.firebaseapp.com',
    storageBucket: 'niramana-setu.firebasestorage.app',
    measurementId: 'G-B0Z3PNKZW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFGw3L9oBa0nw4izcovQR_07cs6STHhYc',
    appId: '1:333671428088:android:b602b1ce5824b02336700d',
    messagingSenderId: '333671428088',
    projectId: 'niramana-setu',
    storageBucket: 'niramana-setu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhSLMLTx0fko_DWYLF_vaFZTfdx4kQGB4',
    appId: '1:333671428088:ios:b20a5cce5328eb3336700d',
    messagingSenderId: '333671428088',
    projectId: 'niramana-setu',
    storageBucket: 'niramana-setu.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhSLMLTx0fko_DWYLF_vaFZTfdx4kQGB4',
    appId: '1:333671428088:ios:b20a5cce5328eb3336700d',
    messagingSenderId: '333671428088',
    projectId: 'niramana-setu',
    storageBucket: 'niramana-setu.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0e8NbSgg2vx_MZfpC9YMZP8BxRVWczp0',
    appId: '1:333671428088:web:31547dd2c8e4194d36700d',
    messagingSenderId: '333671428088',
    projectId: 'niramana-setu',
    authDomain: 'niramana-setu.firebaseapp.com',
    storageBucket: 'niramana-setu.firebasestorage.app',
    measurementId: 'G-FL37TJW0KD',
  );
}
